# Generated by Django 4.1.2 on 2022-10-11 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_gamesession_sport_remove_pitch_game_time_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pitch',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.sport'),
        ),
    ]
