# Generated by Django 4.1.2 on 2022-10-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_message_session_gamesession_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='down',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='up',
            field=models.BigIntegerField(default=0),
        ),
    ]
