# Generated by Django 4.1.2 on 2022-10-14 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0014_message_down_voted_message_up_voted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='pending',
            field=models.ManyToManyField(blank=True, related_name='pending', to=settings.AUTH_USER_MODEL),
        ),
    ]
