# Generated by Django 4.1.2 on 2022-10-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_gamesession_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
